export const GET_PLAYLIST = 'PLAYLIST/GET_PLAYLIST'
export const GET_PLAYLIST_SUCCESS = 'PLAYLIST/GET_PLAYLIST_SUCCESS'
export const GET_PLAYLIST_ERROR = 'PLAYLIST/GET_PLAYLIST_ERROR'
export const GET_PLAYLIST_LOADING = 'PLAYLIST/GET_PLAYLIST_LOADING'
